require("dotenv").config(); 
const express = require("express");
const { MongoClient, ObjectId } = require("mongodb");
const cors = require("cors");
const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);

const app = express();
const port = process.env.PORT || 5000;

// 1. ALLOW CORS FOR FRONTEND DOMAINS
app.use(cors({
  origin: [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://arthub-mauve.vercel.app" 
  ],
  credentials: true,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"]
}));

// Global variables for lazy initialization across Serverless environments
let client;
let db;
let auth;

const uri = process.env.MONGO_DB_URI;
if (!uri) {
  console.error("❌ ERROR: MONGO_DB_URI is undefined inside environment variables.");
}

// Helper to guarantee database pool connectivity is alive inside explicit standalone endpoints
async function ensureDbConnected() {
  if (!client) {
  client = new MongoClient(uri);
}
  if (!db) {
    await client.connect();
    db = client.db("arthub-db");
  }
  return db;
}

// 2.  STRIPE WEBHOOK ENDPOINT (HANDLES SUBSCRIPTIONS & ARTWORK LEDGERS)
app.post("/api/payment/webhook", express.raw({ type: "application/json" }), async (req, res) => {
  const sig = req.headers["stripe-signature"];
  let event;

  try {
    event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    console.error(`❌ Webhook Signature Verification Failed:`, err.message);
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  if (event.type === "checkout.session.completed") {
    const session = event.data.object;

    try {
      await ensureDbConnected();

      // CASE A: User Subscription Handling
      if (session.metadata.tier) {
        const userEmail = String(session.metadata.userEmail).trim().toLowerCase(); 
        const targetTier = session.metadata.tier;
        const totalPaidAmount = session.amount_total ? session.amount_total / 100 : 0;

        await db.collection("user").updateOne(
          { email: userEmail },
          { $set: { subscriptionTier: targetTier, updatedAt: new Date() } }
        );

        const subscriptionTransaction = {
          type: "publishing_fee", 
          userEmail: userEmail,
          amount: totalPaidAmount,
          tier: targetTier,
          date: new Date()
        };

        await db.collection("transactions").insertOne(subscriptionTransaction);
        console.log(`✨ Successfully upgraded ${userEmail} to tier: ${targetTier} & logged transaction.`);
      }

      // CASE B: Artwork Purchase Multi-Role Ledger Generation
      if (session.metadata.type === "artwork_purchase") {
        const meta = session.metadata;
        console.log("📥 Webhook received artwork metadata payload:", meta);

        let originalArtwork = null;
        try {
          const searchId = ObjectId.isValid(meta.artworkId) ? new ObjectId(meta.artworkId) : meta.artworkId;
          originalArtwork = await db.collection("artworks").findOne({ _id: searchId });
        } catch (queryErr) {
          console.error("⚠️ Non-blocking artwork document lookup exception:", queryErr.message);
        }

        const cleanBuyerEmail = String(meta.buyerEmail).trim().toLowerCase();
        const cleanArtistEmail = String(originalArtwork?.artistEmail || meta.artistEmail || "").trim().toLowerCase();

        const existingTx = await db.collection("transactions").findOne({
          userEmail: cleanBuyerEmail,
          artworkId: meta.artworkId,
          type: "purchase"
        });

        if (!existingTx) {
          const purchaseRecord = {
            artworkId: meta.artworkId,
            artworkTitle: originalArtwork?.title || meta.artworkTitle || "Exhibited Composition",
            image: originalArtwork?.image || "", 
            amount: originalArtwork ? parseFloat(originalArtwork.price) : parseFloat(meta.amount || 0),
            userEmail: cleanBuyerEmail, 
            buyerName: meta.buyerName,      
            artistEmail: cleanArtistEmail,  
            artistName: originalArtwork?.artistName || meta.artistName || "Exhibited Creator",
            type: "purchase",               
            date: new Date()
          };

          const insertResult = await db.collection("transactions").insertOne(purchaseRecord);
          console.log(`✅ Transaction successfully logged via Webhook with ID: ${insertResult.insertedId} for user: ${cleanBuyerEmail}`);
        } else {
          console.log(`ℹ️ Webhook execution skipped: Transaction already generated by frontend fallback helper.`);
        }
      }

    } catch (dbErr) {
      console.error("❌ Failed to parse transaction details inside webhook:", dbErr);
      return res.status(500).send("Internal DB adjustment failure");
    }
  }

  res.json({ received: true });
});

app.use(express.json());

// 1. Force Subscription Upgrade Fallback Write Engine
app.post("/api/payment/confirm-subscription", async (req, res) => {
  try {
    await ensureDbConnected();
    const { email, tier } = req.body;
    if (!email || !tier) {
      return res.status(400).json({ success: false, message: "Missing required tracking tokens." });
    }

    const cleanEmail = String(email).trim().toLowerCase();
    const cleanTier = String(tier).trim().toLowerCase();

    await db.collection("user").updateOne(
      { email: cleanEmail },
      { $set: { subscriptionTier: cleanTier, updatedAt: new Date() } }
    );

    const existingTx = await db.collection("transactions").findOne({
      userEmail: cleanEmail,
      type: "publishing_fee",
      tier: cleanTier
    });

    if (!existingTx) {
      const tierPrices = { pro: 9.99, premium: 19.99 };
      await db.collection("transactions").insertOne({
        type: "publishing_fee",
        userEmail: cleanEmail,
        amount: tierPrices[cleanTier] || 0,
        tier: cleanTier,
        date: new Date()
      });
    }

    console.log(`[Bypass Handshake] Successfully forced tier upgrade for ${cleanEmail} -> ${cleanTier}`);
    return res.status(200).json({ success: true, tier: cleanTier });
  } catch (err) {
    console.error("Local sync subscriber routing exception:", err);
    return res.status(500).json({ success: false, message: err.message });
  }
});

// 2. Force Artwork Purchase Fallback Write Engine
app.post("/api/payment/confirm-purchase", async (req, res) => {
  try {
    await ensureDbConnected();
    const { buyerEmail, buyerName, artworkId } = req.body;
    if (!buyerEmail || !artworkId) {
      return res.status(400).json({ success: false, message: "Missing required fields." });
    }

    const cleanBuyerEmail = String(buyerEmail).trim().toLowerCase();

    const artwork = await db.collection("artworks").findOne({
      _id: ObjectId.isValid(artworkId) ? new ObjectId(artworkId) : artworkId
    });

    if (!artwork) {
      return res.status(404).json({ success: false, message: "Artwork not found." });
    }

    const existing = await db.collection("transactions").findOne({
      userEmail: cleanBuyerEmail,
      artworkId: artworkId.toString(),
      type: "purchase"
    });

    if (existing) {
      return res.status(200).json({ success: true, alreadyRecorded: true });
    }

    const cleanArtistEmail = String(artwork.artistEmail || "").trim().toLowerCase();

    const purchaseRecord = {
      artworkId: artworkId.toString(),
      artworkTitle: artwork.title,
      image: artwork.image || "",
      amount: parseFloat(artwork.price),
      userEmail: cleanBuyerEmail,
      buyerName: buyerName || "Anonymous Collector",
      artistEmail: cleanArtistEmail,
      artistName: artwork.artistName || "Exhibited Creator",
      type: "purchase",
      date: new Date()
    };

    await db.collection("transactions").insertOne(purchaseRecord);
    console.log(`✅ Fallback confirm-purchase recorded for ${cleanBuyerEmail} → "${artwork.title}"`);

    return res.status(201).json({ success: true });
  } catch (err) {
    console.error("Local sync purchase logging failure:", err);
    return res.status(500).json({ success: false, message: err.message });
  }
});

// 4. DATABASE & AUTH ENGINE POOL INITIALIZATION MIDDLEWARE
app.use(async (req, res, next) => {
  try {
    await ensureDbConnected();
    if (!auth) {
      // Dynamic import solves ERR_REQUIRE_ESM since middleware is an async runtime function
      const { betterAuth } = await import("better-auth");
      const { mongodbAdapter } = await import("better-auth/adapters/mongodb");

      auth = betterAuth({
  database: mongodbAdapter(db, {
    client,
    collections: { user: "user" }
  }),
  advanced: {
    crossSubdomainCookie: true 
  },
 
  trustedOrigins: [
    "http://localhost:3000", 
    "http://127.0.0.1:3000", 
    "https://arthub-mauve.vercel.app",
    "https://arthub-server-ten.vercel.app"
  ],
        user: {
          additionalFields: {
            role: { type: "string", defaultValue: "user", input: false },
          },
        },
        emailAndPassword: { 
          enabled: true,
          autoLinkToProvider: ["google"] 
        },
        socialProviders: {
          google: {
            clientId: process.env.GOOGLE_CLIENT_ID,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET,
          },
        },
      });
    }

    req.db = db;
    req.artworksCollection = db.collection("artworks");
    req.transactionsCollection = db.collection("transactions");
    req.usersCollection = db.collection("user");
    req.authInstance = auth;

    next();
  } catch (error) {
    console.error("Serverless Database handshake exception:", error);
    res.status(500).json({ success: false, message: "Database connection failed." });
  }
});

// Endpoint A: Subscription Tier Plan Payments
app.post("/api/payment/create-checkout", async (req, res) => {
  try {
    const { email, tier, priceAmount } = req.body;
    if (!email || !tier) {
      return res.status(400).json({ success: false, message: "Missing tracking attributes." });
    }

    const frontendUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

    const session = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      mode: "payment",
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: `ArtHub ${tier.toUpperCase()} Tier Membership Upgrade`,
              description: `Unlocks complete upload capacity limits tailored to your specific account needs.`,
            },
            unit_amount: Math.round(priceAmount * 100),
          },
          quantity: 1,
        },
      ],
      metadata: { userEmail: email.trim().toLowerCase(), tier: tier },
      success_url: `${frontendUrl}/dashboard/user?payment_success=true&tier=${tier}`,
      cancel_url: `${frontendUrl}/dashboard/user?payment_cancelled=true`,
    });

    res.status(200).json({ success: true, url: session.url });
  } catch (err) {
    console.error("Stripe Checkout Crash:", err.message);
    res.status(500).json({ success: false, message: err.message });
  }
});

// Endpoint B: Artwork Purchase Flow with Tier Checking Limits Guard
app.post("/api/payment/create-artwork-checkout", async (req, res) => {
  try {
    const { buyerEmail, buyerName, artworkId } = req.body;

    if (!buyerEmail || !artworkId) {
      return res.status(400).json({ success: false, message: "Missing tracking parameters." });
    }

    const artwork = await req.artworksCollection.findOne({ 
      _id: ObjectId.isValid(artworkId) ? new ObjectId(artworkId) : artworkId 
    });
    if (!artwork) {
      return res.status(404).json({ success: false, message: "Artwork missing from catalog." });
    }

    const cleanBuyerEmail = String(buyerEmail).trim().toLowerCase();
    const userProfile = await req.usersCollection.findOne({ email: cleanBuyerEmail });
    const tier = userProfile?.subscriptionTier || "free";

    if (tier === "free" || tier === "pro") {
      const currentPurchasesCount = await req.transactionsCollection.countDocuments({ 
        userEmail: cleanBuyerEmail, 
        type: "purchase" 
      });

      const maxLimit = tier === "free" ? 3 : 9;
      if (currentPurchasesCount >= maxLimit) {
        return res.status(403).json({ 
          success: false, 
          message: `Acquisition cap reached! Your current ${tier} plan limits you to ${maxLimit} artworks. Please upgrade.` 
        });
      }
    }

    const frontendUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

    const session = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      mode: "payment",
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: artwork.title,
              description: `Original masterwork compiled by artist ${artwork.artistName || "Exhibited Creator"}.`,
            },
            unit_amount: Math.round(artwork.price * 100),
          },
          quantity: 1,
        },
      ],
      metadata: {
        type: "artwork_purchase",
        artworkId: artworkId.toString(),
        artworkTitle: artwork.title,
        amount: artwork.price.toString(),
        buyerEmail: cleanBuyerEmail,
        buyerName: buyerName || "Anonymous Collector",
        artistEmail: artwork.artistEmail,
        artistName: artwork.artistName || "Exhibited Creator"
      },
      success_url: `${frontendUrl}/dashboard/user?purchase_success=true&artworkId=${artworkId}&buyerName=${encodeURIComponent(buyerName || "Collector")}`,
      cancel_url: `${frontendUrl}/browse?purchase_cancelled=true`,
    });

    res.status(200).json({ success: true, url: session.url });
  } catch (err) {
    console.error("Artwork checkout creation fail:", err.message);
    res.status(500).json({ success: false, message: err.message });
  }
});

// ISOLATED USER PROFILE FETCH WITH CASE-INSENSITIVE EMAIL MATCHING
app.get("/api/user/profile", async (req, res) => {
  try {
    const { email } = req.query;
    if (!email) {
      return res.status(400).json({ success: false, message: "Email query missing." });
    }
    
    const cleanEmail = String(email).trim().toLowerCase();
    const userProfile = await req.usersCollection.findOne({ email: cleanEmail });
    
    if (!userProfile) {
      return res.status(404).json({ success: false, message: "Profile match not found." });
    }
    
    res.status(200).json({ success: true, user: userProfile });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// 1. Fetch Comments for an Artwork
app.get("/api/artworks/:id/comments", async (req, res) => {
  try {
    const comments = await req.db.collection("comments")
      .find({ artworkId: req.params.id })
      .sort({ createdAt: -1 })
      .toArray();
    res.status(200).json({ success: true, comments });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// 2. Post a Comment
app.post("/api/artworks/:id/comments", async (req, res) => {
  try {
    const { userName, userEmail, text } = req.body;
    const artworkId = req.params.id;
    const cleanBuyerEmail = String(userEmail).trim().toLowerCase();

    if (!text || !userEmail) {
      return res.status(400).json({ success: false, message: "Missing essential comment attributes." });
    }

    const purchaseRecord = await req.transactionsCollection.findOne({
      userEmail: cleanBuyerEmail,
      artworkId: artworkId.toString(),
      type: "purchase"
    });

    if (!purchaseRecord) {
      return res.status(403).json({ 
        success: false, 
        message: "Exclusive feature: Only collectors who purchased this artwork can leave commentary." 
      });
    }

    const commentDoc = {
      artworkId: artworkId,
      userName: userName || "Anonymous Collector",
      userEmail: cleanBuyerEmail,
      comment: text, 
      createdAt: new Date()
    };

    await req.db.collection("comments").insertOne(commentDoc);
    res.status(201).json({ success: true, comment: commentDoc });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// 3. Edit an Existing Comment
app.put("/api/comments/:commentId", async (req, res) => {
  try {
    const { commentId } = req.params;
    const { text, userEmail } = req.body;
    const cleanEmail = String(userEmail).trim().toLowerCase();

    const targetComment = await req.db.collection("comments").findOne({ _id: new ObjectId(commentId) });
    if (!targetComment) return res.status(404).json({ success: false, message: "Comment not found." });

    if (targetComment.userEmail !== cleanEmail) {
      return res.status(401).json({ success: false, message: "Unauthorized action." });
    }

    await req.db.collection("comments").updateOne(
      { _id: new ObjectId(commentId) },
      { $set: { comment: text, updatedAt: new Date() } }
    );
    res.status(200).json({ success: true });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// 4. Delete a Comment
app.delete("/api/comments/:commentId", async (req, res) => {
  try {
    const { commentId } = req.params;
    const { userEmail } = req.body; 
    const cleanEmail = String(userEmail).trim().toLowerCase();

    const targetComment = await req.db.collection("comments").findOne({ _id: new ObjectId(commentId) });
    if (!targetComment) return res.status(404).json({ success: false, message: "Comment not found." });

    if (targetComment.userEmail !== cleanEmail) {
      return res.status(401).json({ success: false, message: "Unauthorized action." });
    }

    await req.db.collection("comments").deleteOne({ _id: new ObjectId(commentId) });
    res.status(200).json({ success: true });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// TOP ARTISTS AGGREGATION PIPELINE
app.get("/api/artists/top", async (req, res) => {
  try {
    const topArtists = await req.transactionsCollection.aggregate([
      { $match: { type: "purchase" } },
      {
        $group: {
          _id: "$artistEmail",
          artistName: { $first: "$artistName" },
          totalSalesVolume: { $sum: "$amount" },
          artworksCount: { $sum: 1 }
        }
      },
      { $sort: { totalSalesVolume: -1 } },
      { $limit: 3 }
    ]).toArray();

    res.status(200).json({ success: true, artists: topArtists });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.post("/api/auth/register-direct", async (req, res) => {
  try {
    const { name, email, password, role } = req.body;
    const cleanEmail = String(email).trim().toLowerCase();
    
    const existingUser = await req.usersCollection.findOne({ email: cleanEmail });
    if (existingUser) {
      return res.status(400).json({ success: false, message: "Email is already registered." });
    }

    const { randomBytes, scrypt } = require("crypto");
    const salt = randomBytes(16).toString("hex");
    const key = await new Promise((resolve, reject) => {
      scrypt(password.normalize("NFKC"), salt, 64, { N: 16384, r: 16, p: 1, maxmem: 128 * 16384 * 16 * 2 }, (err, k) => err ? reject(err) : resolve(k));
    });
    const hashedPassword = `${salt}:${key.toString("hex")}`;

    const userId = new ObjectId();
    await req.usersCollection.insertOne({
      _id: userId,
      name,
      email: cleanEmail,
      emailVerified: false,
      role: role || "user",
      subscriptionTier: "free", 
      createdAt: new Date(),
      updatedAt: new Date()
    });

    const accountCollection = req.db.collection("account");
    await accountCollection.insertOne({
      _id: new ObjectId(),
      userId: userId,
      accountId: cleanEmail,
      providerId: "credential",
      password: hashedPassword,
      createdAt: new Date(),
      updatedAt: new Date()
    });

    return res.status(201).json({ success: true, message: "Registered successfully!" });
  } catch (err) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

app.all(/^\/api\/auth(?:\/(.*))?$/, async (req, res) => {
  try {
    // 💡 FIX: Read the forwarded host if it exists, otherwise fall back to standard host
    const host = req.headers["x-forwarded-host"] || req.get("host");
    
    // Also check if the protocol was forwarded (Vercel uses https)
    const protocol = req.headers["x-forwarded-proto"] || req.protocol;
    
    const fullUrl = `${protocol}://${host}${req.originalUrl}`;
    
    const webRequest = new Request(fullUrl, {
      method: req.method,
      headers: new Headers(req.headers),
      body: ["GET", "HEAD"].includes(req.method) ? undefined : JSON.stringify(req.body)
    });

    const webResponse = await req.authInstance.handler(webRequest); 
    webResponse.headers.forEach((value, key) => res.setHeader(key, value));
    res.status(webResponse.status);
    return res.send(await webResponse.text());
  } catch (err) {
    console.error("Internal auth engine failure:", err);
    return res.status(500).json({ success: false, message: "Internal auth engine failure" });
  }
});

app.get("/api/artworks", async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 100;
    let artworks = (limit === 6)
      ? await req.artworksCollection.aggregate([{ $sample: { size: 6 } }]).toArray()
      : await req.artworksCollection.find({}).sort({ createdAt: -1 }).limit(limit).toArray();
    res.status(200).json({ success: true, artworks });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/artworks/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const query = ObjectId.isValid(id) ? { _id: new ObjectId(id) } : { _id: id };
    const artwork = await req.artworksCollection.findOne(query);
    if (!artwork) return res.status(404).json({ success: false, message: "Record missing." });
    res.status(200).json({ success: true, artwork });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/user/purchases", async (req, res) => {
  try {
    const { email } = req.query;
    const cleanSearchEmail = String(email).trim().toLowerCase(); 
    const history = await req.transactionsCollection.find({ userEmail: cleanSearchEmail, type: "purchase" }).toArray();
    res.status(200).json({ success: true, history });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/user/transactions", async (req, res) => {
  try {
    const { email } = req.query;
    if (!email) {
      return res.status(400).json({ success: false, message: "Email query missing." });
    }
    const cleanSearchEmail = String(email).trim().toLowerCase();
    const allTransactions = await req.transactionsCollection
      .find({ userEmail: cleanSearchEmail })
      .sort({ date: -1 })
      .toArray();
    res.status(200).json({ success: true, transactions: allTransactions });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/artist/artworks", async (req, res) => {
  try {
    const { email } = req.query;
    const cleanSearchEmail = String(email).trim().toLowerCase();
    const artworks = await req.artworksCollection.find({ artistEmail: cleanSearchEmail }).toArray();
    res.status(200).json({ success: true, artworks });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.post("/api/artworks", async (req, res) => {
  try {
    const cleanArtistEmail = String(req.body.artistEmail).trim().toLowerCase();
    const newArtwork = { ...req.body, artistEmail: cleanArtistEmail, price: parseFloat(req.body.price), createdAt: new Date() };
    const result = await req.artworksCollection.insertOne(newArtwork);
    res.status(201).json({ success: true, insertedId: result.insertedId });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.put("/api/artworks/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const updateData = { ...req.body, price: parseFloat(req.body.price) };
    if (updateData.artistEmail) updateData.artistEmail = String(updateData.artistEmail).trim().toLowerCase();
    delete updateData._id;
    const result = await req.artworksCollection.updateOne(
      { _id: ObjectId.isValid(id) ? new ObjectId(id) : id },
      { $set: updateData }
    );
    res.status(200).json({ success: true, updated: result.modifiedCount });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.delete("/api/artworks/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const result = await req.artworksCollection.deleteOne({ _id: ObjectId.isValid(id) ? new ObjectId(id) : id });
    res.status(200).json({ success: true, deletedCount: result.deletedCount });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/admin/analytics", async (req, res) => {
  try {
    const totalUsers = await req.usersCollection.countDocuments({ role: "user" });
    const totalArtists = await req.usersCollection.countDocuments({ role: "artist" });
    const salesData = await req.transactionsCollection.find({ type: "purchase" }).toArray();
    const totalArtworksSold = salesData.length;
    const totalRevenue = salesData.reduce((sum, tx) => sum + (tx.amount || 0), 0);
    const categoryAggregation = await req.artworksCollection.aggregate([{ $group: { _id: "$category", count: { $sum: 1 } } }]).toArray();

    res.status(200).json({
      success: true,
      analytics: { totalUsers, totalArtists, totalArtworksSold, totalRevenue },
      categoriesChart: categoryAggregation
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/admin/users", async (req, res) => {
  try {
    const users = await req.usersCollection.find({}).toArray();
    res.status(200).json({ success: true, users });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.patch("/api/admin/users/:id/role", async (req, res) => {
  try {
    const { id } = req.params;
    const { role } = req.body;
    const result = await req.usersCollection.updateOne({ _id: new ObjectId(id) }, { $set: { role: role } });
    res.status(200).json({ success: true, updated: result.modifiedCount });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/api/admin/transactions", async (req, res) => {
  try {
    const transactions = await req.transactionsCollection.find({}).sort({ date: -1 }).toArray();
    res.status(200).json({ success: true, transactions });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.get("/", (req, res) => {
  res.send("ArtHub Express Backend Gateway is Operational.");
});

app.listen(port, () => {
  console.log(` Independent API node broadcasting dynamically on port ${port}`);
});

module.exports = app;